name: airflow_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python<=3.8.7
  - pip==20.2.4
  - pip:
    - -c "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt"
    - apache-airflow[postgres,ssh]==2.0.1
    